### ISSUE TITLE
content属性常见的用法

### ISSUE THREAD

**Issue by oliveying** [oliveying/knowledge#39]
## content用法

1. 清除浮动，具体用法（https://www.zhangxinxu.com/wordpress/2014/06/understand-css-clear-left-right-and-use/）
2. 小三角气泡
3. 字体图标（浏览器自带的特殊符号，外部引入的字体图标）
4. 暂无数据提示，或者title

### 1. 加载中... 动画
```css
.loading:after {
    content: ".";
    animation: loading 2s ease infinite;
}
 
@keyframes loading {
    33% {
        content: "..";
    }
    66% {
        content: "...";
    }
}
 
```
```html
<div class="loading">加载中</div>
```
![20210731172044](https://github.com/oliveying/knowledge/assets/19582572/842ee6eb-cecc-4f0b-b9ef-89f54d9a1000)

animation 动画值含义：

loading：animation-name，规定需要绑定到选择器的 keyframe 名称为 loading。
2s：animation-duration，规定完成动画所花费的时间 2 秒。
ease：animation-timing-function，规定动画的速度曲线，先慢中快后慢。
infinite：animation-iteration，规定动画应该播放的次数为无限次。
通过 animation 动画完成 33%、66% 时与 content 内容配合，实现动态 “加载中...” 的效果。

### 2. 插入图片
* 除了插入字体图标，content 还可以使用 url() 方法插入图片，和 background 属性类似可以使用 url 指定一个图片路径，不同的是 content 属性无法控制图片大小，使用条件有限。
```css
.loading:before {
    content: url("../static/img/loading.gif");
    vertical-align: middle;
}
```

### 3. attr属性内容生成

```css
.test:after {
    content: "（"attr(href)"）"
}
```
```html
<a class="test" href="https://test.cc">test</a>
```
![image](https://github.com/oliveying/knowledge/assets/19582572/bd181b6b-5475-4822-a3c6-5f5e346a1ea6)

### 4. 半边特效

```css
span{
    font-family: sans-serif;
    font-size: 30px;
    font-weight: bold;
    position: relative;
    color: green;
    line-height: 1;
 height: 32px;
display: inline-block;
}
span:before{
    content: attr(text);
    color: orange;
    position: absolute;
    left: 0;
    top: 0;
    width: 50%;
    overflow: hidden;
    line-height: 1;
    height: 32px;
}
```
```html
<span text="olive">olive</span>
<span text="中">中</span>
<span text="文">文</span>

```
![image](https://github.com/oliveying/knowledge/assets/19582572/5dd5fc00-aa9d-4a3d-a495-aebe8d5da98d)

### 5. 文字引号
* 利用元素的 quotes 属性指定双引号，使用 content 的 open-quote 属性值设置开口引号，close-quote 属性值设置闭合引号，当然 quotes 也可以指定其他符号。
```css
span {
    quotes: '“' '”';
}
span:before {
    content: open-quote;
}
span:after {
    content: close-quote;
}
```
```html
<p>李莲花说：<span>江山多年,变化万千,去去重去去,来时是来时</span></p>
```
![image](https://github.com/oliveying/knowledge/assets/19582572/5207abeb-8513-45bf-97c2-7f46b6332834)

### 6. 添加章节数
```css
ul{
    counter-reset: section;
}
li{
    list-style-type: none;
    counter-increment: section;
}
li:before{
    content: counters(section, '-') '.';
}
```
```html
<ul>
    <li class="">章节一</li>
    <li>章节二
        <ul>
            <li>章节二一</li>
            <li>章节二二</li>
            <li>章节二三</li>
        </ul>
    </li>
    <li>章节三</li>
</ul>
```
![image](https://github.com/oliveying/knowledge/assets/19582572/6b5fa851-120b-4d12-b8c4-53857b3f1340)
> 详情查看张鑫旭 http://www.zhangxinxu.com/wordpress/?p=4303

### 7. 计算 checkbox 选中数
* 巧妙运用计数器配合:checked 伪类，选中计数器增加 1，取消选中减 1，用 CSS 实现动态计数功能。

```css
<!--css-->
form {
    counter-reset: count 0;
}
input[type="checkbox"]:checked {
    counter-increment: count 1;
}

.result:after {
    content: counter(count);
}
```
> https://www.zhangxinxu.com/wordpress/2014/08/css-counters-automatic-number-content/
